CRUD.Mvc/Controllers/PaiController.cs
using CRUD.Model.Model;
using CRUD.Model.ModelsDao;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace CRUD.Mvc.Controllers
{
    public class PaiController : Controller
    {
        PaiDao pd = new PaiDao();

        // GET: Pai
        public ActionResult Index()
        {
            var pais = pd.RetornaTodos();

            List<Pai> listPai = new List<Pai>();

            foreach (DataRow i in pais.Rows)
            {
                Pai p = new Pai
                {
                    Id = Int32.Parse(i["id"].ToString()),
                    Nome = i["nome"].ToString(),
                    Cpf = i["cpf"].ToString()
                };

                listPai.Add(p);
            }

            return View(listPai);
        }

        // GET: Pai/Details/5
        public ActionResult Details(int id)
        {
            var pai = new Pai();

            foreach (DataRow i in pd.GetById(id).Rows)
            {
                pai.Id = Int32.Parse(i["id"].ToString());
                pai.Nome = i["nome"].ToString();
                pai.Cpf = i["cpf"].ToString();
            }

            return View(pai);
        }

        // GET: Pai/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pai/Create
        [HttpPost]
        public ActionResult Create(Pai pai)
        {
            try
            {
                pd.Insert(pai);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pai/Edit/5
        public ActionResult Edit(int id)
        {
            var pai = new Pai();

            foreach (DataRow i in pd.GetById(id).Rows)
            {
                pai.Id = Int32.Parse(i["id"].ToString());
                pai.Nome = i["nome"].ToString();
                pai.Cpf = i["cpf"].ToString();
            }

            return View(pai);
        }

        // POST: Pai/Edit/5
        [HttpPost]
        public ActionResult Edit(Pai pai)
        {
            try
            {
                pd.Edit(pai);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pai/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                pd.Delete(id);

                return RedirectToAction("Index");
            } catch(Exception ex)
            {
                return RedirectToAction("Error");
                throw ex;
            }
        }

        public ActionResult Error()
        {
            ViewBag.Error = "Erro ao executar ação.";
            return View();
        }
    }
}

CRUD.Mvc/Views/Pai/Create.cshtml
@model CRUD.Model.Model.Pai

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Pai", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRUD.Mvc/Views/Pai/Details.cshtml
@model CRUD.Model.Model.Pai

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CRUD.Mvc/Views/Pai/Edit.cshtml
@model CRUD.Model.Model.Pai

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Pai", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRUD.Mvc/Views/Pai/Index.cshtml
@model IEnumerable<CRUD.Model.Model.Pai>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cpf)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cpf)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>