CRUD.Mvc/Controllers/FilhoController.cs
using CRUD.Model.Model;
using CRUD.Model.ModelsDao;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Mvc.Controllers
{
    public class FilhoController : Controller
    {
        FilhoDao DB = new FilhoDao();
        PaiDao PaiDao = new PaiDao();

        // GET: filho
        public ActionResult Index()
        {
            var filhos = DB.RetornaTodos();

            List<Filho> listfilho = new List<Filho>();

            foreach (DataRow i in filhos.Rows)
            {
                Pai p = new Pai
                {
                    Id = Int32.Parse(i["paiId"].ToString()),
                    Nome = i["paiNome"].ToString(),
                    Cpf = i["paiCpf"].ToString()
                };

                Filho f = new Filho
                {
                    Id = Int32.Parse(i["filhoId"].ToString()),
                    Nome = i["filhoNome"].ToString(),
                    Idade = i["filhoIdade"].ToString(),
                    Pai = p
                };

                listfilho.Add(f);
            }

            return View(listfilho);
        }

        // GET: filho/Details/5
        public ActionResult Details(int id)
        {
            var filho = new Filho();

            foreach (DataRow i in DB.GetById(id).Rows)
            {
                filho.Id = Int32.Parse(i["filhoId"].ToString());
                filho.Nome = i["filhoNome"].ToString();
                filho.Idade = i["filhoIdade"].ToString();
            }

            return View(filho);
        }

        // GET: filho/Create
        public ActionResult Create()
        {
            var pais = PaiDao.RetornaTodos();
            var listPais = new List<Pai>();

            foreach (DataRow i in pais.Rows)
            {
                var pai = new Pai
                {
                    Id = Int32.Parse(i["id"].ToString()),
                    Nome = i["nome"].ToString(),
                    Cpf = i["cpf"].ToString()
                };

                listPais.Add(pai);
            }

            ViewBag.Pais = new SelectList(listPais, "Id", "Nome");

            return View();
        }

        // POST: filho/Create
        [HttpPost]
        public ActionResult Create(Filho filho, int idPai)
        {
            try
            {
                var pai = new Pai();
                
                foreach (DataRow i in PaiDao.GetById(idPai).Rows)
                {
                    pai.Id = Int32.Parse(i["id"].ToString());
                    pai.Nome = i["nome"].ToString();
                    pai.Cpf = i["cpf"].ToString();
                }

                filho.Pai = pai;

                DB.Insert(filho);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: filho/Edit/5
        public ActionResult Edit(int id)
        {
            var filho = new Filho();
            var pais = new List<Pai>();

            foreach (DataRow i in PaiDao.RetornaTodos().Rows)
            {
                var pai = new Pai
                {
                    Id = Int32.Parse(i["id"].ToString()),
                    Nome = i["nome"].ToString(),
                    Cpf = i["cpf"].ToString()
                };

                pais.Add(pai);
            }

            foreach (DataRow i in DB.GetById(id).Rows)
            {
                var pai = new Pai
                {
                    Id = Int32.Parse(i["paiId"].ToString()),
                    Nome = i["paiNome"].ToString(),
                    Cpf = i["paiCpf"].ToString()
                };

                filho.Id = Int32.Parse(i["filhoId"].ToString());
                filho.Nome = i["filhoNome"].ToString();
                filho.Idade = i["filhoIdade"].ToString();
                filho.Pai = pai;
            }

            ViewBag.Pais = new SelectList(pais, "Id", "Nome", filho.Pai.Id);

            return View(filho);
        }

        // POST: filho/Edit/5
        [HttpPost]
        public ActionResult Edit(Filho filho, int idPai)
        {
            try
            {
                var pai = new Pai();
                foreach (DataRow i in PaiDao.GetById(idPai).Rows)
                {
                    pai.Id = Int32.Parse(i["id"].ToString());
                    pai.Nome = i["nome"].ToString();
                    pai.Cpf = i["cpf"].ToString();
                }

                filho.Pai = pai;

                DB.Edit(filho);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: filho/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                DB.Delete(id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
                throw ex;
            }
        }

        public ActionResult Error()
        {
            ViewBag.Error = "Erro ao executar ação.";
            return View();
        }
    }
}

CRUD.Mvc/Views/Filho/Create.cshtml
@model CRUD.Model.Model.Filho

@{
    ViewBag.Title = "Create";

    var pais = (SelectList) ViewBag.Pais;
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Filho", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filho</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Pais", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idPai", pais, "-- Selecione", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRUD.Mvc/Views/Filho/Details.cshtml
@model CRUD.Model.Model.Filho

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Filho</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CRUD.Mvc/Views/Filho/Edit.cshtml
@model CRUD.Model.Model.Filho

@{
    ViewBag.Title = "Edit";

    var pais = (SelectList) ViewBag.Pais;
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Filho", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Filho</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Pais", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idPai", pais, "-- Selecione", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CRUD.Mvc/Views/Filho/Index.cshtml
@model IEnumerable<CRUD.Model.Model.Filho>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pai.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Idade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pai.Nome)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>